version: "3.6"
services:

  training-elasticsearch:
    container_name: training-elasticsearch
    image: training-elasticsearch
    build:
      context: ./elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_CONNECT_RETRY=300
      - KIBANA_CONNECT_RETRY=300
      - LOGSTASH_START=1
      - KIBANA_START=1

  training-postgres-db:
    container_name: training-postgres-db
    image: training-postgres-db
    build: ./postgres
    command: postgres -c 'max_connections=500'
    ports:
    - '65433:5432'

  training-minio:
    container_name: training-minio
    image: minio/minio:RELEASE.2021-12-20T22-07-16Z
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/results && /usr/bin/docker-entrypoint.sh minio server /data --console-address ":9010"'
    environment:
      MINIO_ROOT_USER: 'hBxJQhCnGJbuEucRhMzq'
      MINIO_ROOT_PASSWORD: 'FDKUGzgfAXk9kBnparMKEPvUiu9yUBwneTq9w29n'
    ports:
      - 9003:9000
      - 9010:9010

networks:
  default:
    name: training_local
