version: "3.6"
services:

  training-elasticsearch:
    container_name: training-elasticsearch
    image: training-elasticsearch
    build:
      context: ./elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_CONNECT_RETRY=300
      - KIBANA_CONNECT_RETRY=300
      - LOGSTASH_START=1
      - KIBANA_START=1

networks:
  default:
    name: training_local
