version: '3.7'

services:
  es:
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_CONNECT_RETRY=300
      - KIBANA_CONNECT_RETRY=300
      - LOGSTASH_START=1
      - KIBANA_START=1
